FROM node:latest
WORKDIR /app
COPY package.json .
RUN npm install
COPY . /app
EXPOSE 80
CMD ["node", "server.js"]




# sudo docker build -t ap20220174-img1 .
# sudo docker images
# sudo docker run -p 3000:80 -d --name ap20220174-cont1 ap20220174-img1
# sudo docker ps
# sudo docker stop ap20220174-cont1
# sudo docker volume create ap20220174-vol
# sudo docker run -d -p 5000:80 --name ap20220174-vol-cont1 -v ap20220174-vol:/app/feedback ap20220174-img1
# sudo docker ps
# 
# localhost:5000 u mozili